apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app-deployment
  labels:
    app: my-devops-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
      - name: my-devops-app
        image: telesameer/my-devops-app:latest
        ports:
        - containerPort: 3000