apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app-deployment
  labels:
    app: CI-CD-Pipeline-with-Jenkins-Docker-and-Kubernetes
spec:
  replicas: 1 # You can increase this for more instances
  selector:
    matchLabels:
      app: CI-CD-Pipeline-with-Jenkins-Docker-and-Kubernetes
  template:
    metadata:
      labels:
        app: CI-CD-Pipeline-with-Jenkins-Docker-and-Kubernetes
    spec:
      containers:
      - name: CI-CD-Pipeline-with-Jenkins-Docker-and-Kubernetes
        image: telesameer/CI-CD-Pipeline-with-Jenkins-Docker-and-Kubernetes:latest # REPLACE with your Docker Hub username
        ports:
        - containerPort: 3000