apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app-deployment
  labels:
    app: my-devops-app
spec:
  replicas: 1 # You can increase this for more instances
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
      - name: my-devops-app
        image: your-dockerhub-username/my-devops-app:latest # REPLACE with your Docker Hub username
        ports:
        - containerPort: 3000