# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-devops-app-service
spec:
  selector:
    app: CI-CD-Pipeline-with-Jenkins-Docker-and-Kubernetes
  type: NodePort # Use LoadBalancer for cloud environments, or ClusterIP for internal services
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 3000 # Container port
      nodePort: 30001 # Optional: specific port on the node (must be in range 30000-32767)