apiVersion: v1
kind: Service
metadata:
  name: my-devops-app-service
spec:
  selector:
    app: my-devops-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000 
      nodePort: 30001